const MAPS = {
  guandu: {
    name: "官渡之战",
    desc: "袁绍与曹操相持于官渡，逐鹿中原",
    startDesc: "袁本初坐拥冀州，兵精粮足，麾下颜良文丑皆是上将。",
    cells: [
      { id: 1, type: "start", name: "邺城", cityTier: null, desc: "袁绍根据地，冀州治所，城池坚固，粮草充沛。" },
      { id: 2, type: "city", name: "白马", cityTier: "low", desc: "黄河要津，颜良率军驻守，曹操首战攻克之地。" },
      { id: 3, type: "empty", name: "黎阳", cityTier: null, desc: "渡河要冲，两军交锋的前哨阵地。" },
      { id: 4, type: "city", name: "延津", cityTier: "mid", desc: "白马以东要地，文丑战死之所，战略价值极高。" },
      { id: 5, type: "event", name: "乌巢", cityTier: null, desc: "袁军粮草重地，曹操夜袭焚粮，一举扭转战局！" },
      { id: 6, type: "city", name: "酸枣", cityTier: "low", desc: "曹操大营所在地，于禁在此设伏。" },
      { id: 7, type: "recruit", name: "募兵", cityTier: null, desc: "战乱纷纷，英雄豪杰纷纷投军。" },
      { id: 8, type: "city", name: "濮阳", cityTier: "mid", desc: "曹操曾久攻不下，后因吕布内乱而得。" },
      { id: 9, type: "empty", name: "仓亭", cityTier: null, desc: "袁军溃败之地，曹军乘胜追击。" },
      { id: 10, type: "casino", name: "赌坊", cityTier: null, desc: "军中消遣，胜则奖赏，败则空耗。" },
      { id: 11, type: "city", name: "许都", cityTier: "high", desc: "曹操挟天子以令诸侯，汉室正统所在。" },
      { id: 12, type: "city", name: "陈留", cityTier: "low", desc: "曹操起兵之地，十八路诸侯会盟之所。" },
      { id: 13, type: "empty", name: "武平", cityTier: null, desc: "袁术败逃路线，遗留大量金银。" },
      { id: 14, type: "event", name: "奇袭", cityTier: null, desc: "夜深人静，敌军营地火光冲天！" },
      { id: 15, type: "city", name: "官渡", cityTier: "mid", desc: "两军对峙主战场，谋士荀彧献计烧粮。" },
      { id: 16, type: "recruit", name: "招贤", cityTier: null, desc: "求贤若渴，天下英才皆可归附。" },
      { id: 17, type: "city", name: "南坡", cityTier: "low", desc: "曹军伏击袁军之处，以少胜多。" },
      { id: 18, type: "empty", name: "西山", cityTier: null, desc: "地势险要，可伏兵十万。" },
      { id: 19, type: "casino", name: "营赌", cityTier: null, desc: "将士们赌酒论英雄。" },
      { id: 20, type: "city", name: "邺城", cityTier: "high", desc: "袁绍老巢，粮草堆积如山，城高池深。" },
      { id: 21, type: "empty", name: "斥章", cityTier: null, desc: "袁绍优柔寡断，错失良机之地。" },
      { id: 22, type: "city", name: "南皮", cityTier: "mid", desc: "袁谭驻守，城墙坚固。" },
      { id: 23, type: "event", name: "风云", cityTier: null, desc: "天象异变，战局即将逆转！" },
      { id: 24, type: "city", name: "平原", cityTier: "low", desc: "刘备曾驻兵此处，与袁绍遥相呼应。" },
      { id: 25, type: "recruit", name: "义从", cityTier: null, desc: "忠义之士，不远千里来投。" },
      { id: 26, type: "city", name: "乐陵", cityTier: "low", desc: "袁熙驻守，偏居一隅。" },
      { id: 27, type: "empty", name: "厌次", cityTier: null, desc: "袁绍撤军途中，溃不成军。" },
      { id: 28, type: "casino", name: "散金", cityTier: null, desc: "千金散去还复来，战场机遇难测。" },
      { id: 29, type: "event", name: "天降", cityTier: null, desc: "福星高照，洪福齐天！" },
      { id: 30, type: "empty", name: "大营", cityTier: null, desc: "得胜还朝，犒赏三军。" },
    ]
  },

  chibi: {
    name: "赤壁之战",
    desc: "孙刘联军大破曹军，三分天下之势已成",
    startDesc: "曹操率八十万大军南下，欲一统天下，孙权刘备共拒曹兵。",
    cells: [
      { id: 1, type: "start", name: "襄阳", cityTier: null, desc: "曹操荆州大本营，势如破竹。" },
      { id: 2, type: "city", name: "江夏", cityTier: "low", desc: "刘琦驻守，长江防线第一关。" },
      { id: 3, type: "empty", name: "汉津", cityTier: null, desc: "刘备渡江脱险之地。" },
      { id: 4, type: "city", name: "夏口", cityTier: "mid", desc: "孙刘联军会师之所。" },
      { id: 5, type: "event", name: "东风", cityTier: null, desc: "万事俱备，只欠东风！周瑜火攻之计已成！" },
      { id: 6, type: "city", name: "樊口", cityTier: "low", desc: "孙刘联军水寨入口。" },
      { id: 7, type: "casino", name: "水寨赌坊", cityTier: null, desc: "东吴水军赌博之地，胜则犒赏三军。" },
      { id: 8, type: "city", name: "赤壁", cityTier: "high", desc: "千古一战，火烧连环船，孙权周瑜以少胜多！" },
      { id: 9, type: "empty", name: "黄州", cityTier: null, desc: "曹操败走华容道此处。" },
      { id: 10, type: "recruit", name: "江东募兵", cityTier: null, desc: "周瑜招兵买马，扩充水军。" },
      { id: 11, type: "city", name: "乌林", cityTier: "low", desc: "曹操败逃时埋下铜雀台赋诗之地。" },
      { id: 12, type: "city", name: "当阳", cityTier: "mid", desc: "长坂坡之战，张飞喝退曹兵。" },
      { id: 13, type: "event", name: "借箭", cityTier: null, desc: "草船借箭，诸葛亮巧计得十万支箭！" },
      { id: 14, type: "empty", name: "江陵", cityTier: null, desc: "荆州的中心，曹操曾想迁都于此。" },
      { id: 15, type: "city", name: "公安", cityTier: "low", desc: "刘备驻扎，苦心经营。" },
      { id: 16, type: "city", name: "油江", cityTier: "mid", desc: "刘备入川根据地。" },
      { id: 17, type: "recruit", name: "贤才来投", cityTier: null, desc: "凤雏庞统来投，卧龙凤雏齐聚。" },
      { id: 18, type: "empty", name: "陆口", cityTier: null, desc: "东吴水军要塞。" },
      { id: 19, type: "casino", name: "龙门赌局", cityTier: null, desc: "江东豪杰一决高下。" },
      { id: 20, type: "city", name: "柴桑", cityTier: "high", desc: "周瑜大都督府，孙权决意抗曹之地。" },
      { id: 21, type: "empty", name: "鄱阳", cityTier: null, desc: "东吴水军训练场。" },
      { id: 22, type: "event", name: "火攻", cityTier: null, desc: "风火大作，曹操大军灰飞烟灭！" },
      { id: 23, type: "city", name: "南郡", cityTier: "mid", desc: "周瑜攻占，与刘备分地。" },
      { id: 24, type: "city", name: "武陵", cityTier: "low", desc: "刘备收取江南四郡。" },
      { id: 25, type: "casino", name: "乱世赌场", cityTier: null, desc: "时局动荡，豪赌一把。" },
      { id: 26, type: "city", name: "江陵", cityTier: "high", desc: "荆州的中心，战略要地。" },
      { id: 27, type: "empty", name: "巴丘", cityTier: null, desc: "周瑜病逝之处，英雄末路。" },
      { id: 28, type: "recruit", name: "草庐访贤", cityTier: null, desc: "三顾茅庐，请卧龙出山。" },
      { id: 29, type: "city", name: "零陵", cityTier: "mid", desc: "桂阳太守赵范归顺。" },
      { id: 30, type: "event", name: "连环计", cityTier: null, desc: "王允连环计，貂蝉配董卓吕布。" },
      { id: 31, type: "city", name: "桂阳", cityTier: "low", desc: "赵范投降，刘备得此地。" },
      { id: 32, type: "empty", name: "湘江", cityTier: null, desc: "风景秀丽，物产丰饶。" },
      { id: 33, type: "city", name: "长沙", cityTier: "mid", desc: "黄忠归顺，老将出马。" },
      { id: 34, type: "casino", name: "铜雀赌坊", cityTier: null, desc: "曹操铜雀台，宴请群臣。" },
      { id: 35, type: "city", name: "庐江", cityTier: "low", desc: "刘馥被杀，曹操失一臂膀。" },
      { id: 36, type: "event", name: "瘟疫", cityTier: null, desc: "曹军水土不服，瘟疫横行！" },
      { id: 37, type: "empty", name: "濡须", cityTier: null, desc: "孙权据守，曹操难以逾越。" },
      { id: 38, type: "recruit", name: "义勇营", cityTier: null, desc: "招兵买马，扩充实力。" },
      { id: 39, type: "empty", name: "濡须口", cityTier: null, desc: "东吴水军要塞，一夫当关。" },
      { id: 40, type: "event", name: "天命", cityTier: null, desc: "天意弄人，胜负难测！" },
    ]
  },

  hanzhong: {
    name: "汉中之战",
    desc: "刘备与曹操争夺汉中，三国鼎立之势已成",
    startDesc: "曹操平定张鲁据有汉中，刘备进取西川，两雄争锋。",
    cells: [
      { id: 1, type: "start", name: "成都", cityTier: null, desc: "刘备根据地，天府之国。" },
      { id: 2, type: "city", name: "阳平关", cityTier: "low", desc: "汉中门户，一夫当关万夫莫开。" },
      { id: 3, type: "empty", name: "葭萌", cityTier: null, desc: "刘备入蜀第一站。" },
      { id: 4, type: "city", name: "定军山", cityTier: "mid", desc: "黄忠刀劈夏侯渊，一战成名！" },
      { id: 5, type: "event", name: "落石", cityTier: null, desc: "山高路险，滚石檑木从天而降！" },
      { id: 6, type: "recruit", name: "山中隐士", cityTier: null, desc: "隐居山林的高人，或有奇谋相授。" },
      { id: 7, type: "city", name: "沔阳", cityTier: "low", desc: "汉水之滨，鱼米之乡。" },
      { id: 8, type: "casino", name: "军帐赌坊", cityTier: null, desc: "军营消遣，胜者犒赏。" },
      { id: 9, type: "city", name: "南郑", cityTier: "mid", desc: "汉中郡治，张鲁曾据此。" },
      { id: 10, type: "empty", name: "铁山", cityTier: null, desc: "矿产丰富，可铸钱粮。" },
      { id: 11, type: "city", name: "汉中", cityTier: "high", desc: "曹操亲征，刘备退守，两军对峙。" },
      { id: 12, type: "city", name: "褒城", cityTier: "low", desc: "栈道要冲，兵家必争。" },
      { id: 13, type: "event", name: "伏兵", cityTier: null, desc: "树林中杀声四起，有伏兵！" },
      { id: 14, type: "city", name: "武都", cityTier: "mid", desc: "氐族聚居，地势险要。" },
      { id: 15, type: "empty", name: "祁山道", cityTier: null, desc: "诸葛亮北伐路线。" },
      { id: 16, type: "recruit", name: "义士堂", cityTier: null, desc: "招贤纳士，共图大业。" },
      { id: 17, type: "city", name: "下辩", cityTier: "low", desc: "武都属县，蜀魏交界。" },
      { id: 18, type: "casino", name: "蜀道赌局", cityTier: null, desc: "蜀道艰难，赌一把运气。" },
      { id: 19, type: "city", name: "成都", cityTier: "high", desc: "刘备称王，龙椅在此。" },
      { id: 20, type: "event", name: "天象", cityTier: null, desc: "五星连珠，大吉之兆！" },
      { id: 21, type: "empty", name: "梓潼", cityTier: null, desc: "剑门关后第一城。" },
      { id: 22, type: "city", name: "剑阁", cityTier: "mid", desc: "一夫当关万夫莫开，姜维曾守此处。" },
      { id: 23, type: "city", name: "葭萌", cityTier: "low", desc: "刘备入蜀发源地。" },
      { id: 24, type: "recruit", name: "卧龙岗", cityTier: null, desc: "诸葛亮的故居，凤雏也曾来此。" },
      { id: 25, type: "casino", name: "金沙赌场", cityTier: null, desc: "豪商巨贾汇聚之地。" },
      { id: 26, type: "city", name: "白水", cityTier: "low", desc: "蜀道要冲，地势险峻。" },
      { id: 27, type: "event", name: "落雷", cityTier: null, desc: "天雷滚滚，惊天动地！" },
      { id: 28, type: "city", name: "广元", cityTier: "mid", desc: "入蜀咽喉，战略要地。" },
      { id: 29, type: "empty", name: "阴平", cityTier: null, desc: "邓艾偷渡灭蜀之路。" },
      { id: 30, type: "city", name: "长安", cityTier: "high", desc: "曹操称魏王，都于邺城，长安为西京。" },
      { id: 31, type: "city", name: "陈仓", cityTier: "low", desc: "韩信暗度陈仓之处。" },
      { id: 32, type: "recruit", name: "虎牢招兵", cityTier: null, desc: "十八路诸侯曾会盟于此。" },
      { id: 33, type: "casino", name: "关中赌坊", cityTier: null, desc: "三辅之地，繁华富庶。" },
      { id: 34, type: "city", name: "潼关", cityTier: "mid", desc: "马超曾在此大败曹操。" },
      { id: 35, type: "event", name: "奇袭", cityTier: null, desc: "出其不意，攻其不备！" },
      { id: 36, type: "empty", name: "武关", cityTier: null, desc: "入关中三关之一。" },
      { id: 37, type: "city", name: "上庸", cityTier: "low", desc: "刘封孟达驻守之地。" },
      { id: 38, type: "city", name: "房陵", cityTier: "mid", desc: "山路崎岖，易守难攻。" },
      { id: 39, type: "empty", name: "临沮", cityTier: null, desc: "关羽败走麦城之路。" },
      { id: 40, type: "casino", name: "乱世赌坊", cityTier: null, desc: "时局动荡，唯有自强。" },
      { id: 41, type: "city", name: "洛阳", cityTier: "high", desc: "东汉国都，汉室正统所在。" },
      { id: 42, type: "event", name: "天命", cityTier: null, desc: "三分天下，天命已定！" },
      { id: 43, type: "city", name: "新城", cityTier: "low", desc: "刘封曾驻守，后被赐死。" },
      { id: 44, type: "recruit", name: "英雄会", cityTier: null, desc: "天下英雄齐聚，共商大计。" },
      { id: 45, type: "empty", name: "麦城", cityTier: null, desc: "关羽忠义千秋，魂归此处。" },
      { id: 46, type: "city", name: "当阳", cityTier: "mid", desc: "关羽大意失荆州后败走。" },
      { id: 47, type: "event", name: "风云", cityTier: null, desc: "风云突变，战局逆转！" },
      { id: 48, type: "city", name: "公安", cityTier: "low", desc: "刘备经营荆州的据点。" },
      { id: 49, type: "casino", name: "终局赌场", cityTier: null, desc: "胜负已分，天下初定。" },
      { id: 50, type: "empty", name: "永安", cityTier: null, desc: "刘备托孤之地，诸葛亮鞠躬尽瘁。" },
    ]
  }
};
